[tool.black]
line-length=120
skip-string-normalization=false

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=120
profile="black"
known_first_party="text_to_sql"
