name: Python CI

on:
  push:
    branches: [ "main", "add-cicd-and-sentry" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  env-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt; fi
          pip install pytest pylint flake8

  test-and-lint:
    needs: env-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint with pylint
        run: pylint --rcfile=.linting/.pylintrc **/*.py
      - name: Lint with flake8
        run: flake8 --config=.linting/.flake8 **/*.py
      - name: Run tests
        run: pytest tests/test_db_config.py
